### ISSUE TITLE
YAML dinghyfiles are unsupported

### ISSUE THREAD

**Issue by iandelahorne** [armory-io/arm#36]
Dinghy supports YAML (and HCL) templates, but the arm CLI doesn't - it assumes all input is JSON.

Using latest master, I rendered `examples/dinghyfile_basic` into YAML and tried to run it:

```yaml
---
application: helloworldapp
pipelines:
- application: helloworldapp
  name: my-pipeline-name
  stages:
  - name: one
    type: wait
    waitTime: 10
```

```
$ ./arm dinghy render examples/dinghyfile_yaml
INFO[2020-10-27 14:47:28] Checking dinghyfile
INFO[2020-10-27 14:47:28] Parsing dinghyfile
ERRO[2020-10-27 14:47:28] Failed to parse global vars:
 ---
application: helloworldapp
pipelines:
- application: helloworldapp
  name: my-pipeline-name
  stages:
  - name: one
    type: wait
    waitTime: 10  arm-cli-test=
ERRO[2020-10-27 14:47:28] Parsing dinghyfile failed: invalid character '-' in numeric literal
```
